name: Build and Release

on:
  push:
    branches:
      - develop

jobs:
  lookForRelease:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get version number
        uses: nyaa8/package-version@v1.0.3
      
      - name: Get release for current version number
        id: get_release
        uses: joutvhu/get-release@v1.0.1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deleteReleaseAssets:
  needs: lookForRelease
    if: ${{ steps.get_release.outputs.id == null || steps.get_release.outputs.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: deleteReleaseAssets
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # mac_certs: ${{ secrets.MAC_CERTS }}
          # mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}

          release: true
