name: After release

on:
  release:
    types: [published]

jobs:
  afterRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Merge develop -> master
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
