name: After release

on:
  release:
    types: [published]

jobs:
  afterRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Merge develop -> master
        run: |
          git checkout master
          git merge origin/develop
          git push
